config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :amounts

  resources :orders

  resources :line_items do
    put 'decrement', on: :member
    put 'increment', on: :member
  end

  resources :carts

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :brands

  get 'details/index'
  get 'details/show'

  root 'static_pages#home'

  get 'static_pages/contacts'
  get 'static_pages/about'
  get 'static_pages/help'
  get 'static_pages/import'
  get 'static_pages/history'

  resources :details do
    collection { post :import }
    put 'quantity_to_cart', on: :member
  end

  post 'rabats/import'

end

app/views/layouts/_devise.html.erb
<% if user_signed_in? %>
  <span>Здравствуйте, <%= current_user.email %></span>
  <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

app/views/layouts/_footer.html.erb
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2014 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>

app/views/layouts/_importForm.html.erb
  <%= render "layouts/selectBrand" %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import", class: "submitButtn" %>
  

app/views/layouts/_nav.html.erb
<nav class="z-depth-3">
  <%= link_to "Logo", root_path, class: "brand-logo" %>
  <ul class="right hide-on-med-and-down">
    <li>
      <%= link_to "Контакти", static_pages_contacts_path, class: "toFeedback right-align" %>
    </li>
    <li>
      <%= link_to "Допомога", '#help', class: "right-align" %>
    </li>
    <li>
      <a class="dropdown-button" href="#!" data-activates="dropdown1">Додатково<i class="mdi-navigation-arrow-drop-down right"></i></a>
    </li>
    <ul id='dropdown1' class='dropdown-content'>
      <li>
        <%= link_to "Профiль", edit_user_registration_path, class: "right-align" %>
      </li>
      <% if current_user.try(:admin) %>
        <li>
          <%= link_to "Импорт", static_pages_import_path, class: "right-align" %>
        </li>
      <% end %>
      <li>
        <%= link_to "Iсторiя замовлень", static_pages_history_path, class: "right-align" %>
      </li>
    </ul>
  </ul>
</nav>

app/views/layouts/_searchForm.html.erb
			<%= form_tag("/details/index", method: "get") do %>
				<%= render "layouts/selectBrand" %>
				<div class="input-field">
				  <%= text_field_tag(:q) %>
				  <%= label_tag(:q, "Search for:") %>
				</div>
				<div>
				  <%= submit_tag "Search", class:"btn btn-submit" %>
				</div>
			<% end %>

app/views/layouts/_selectBrand.html.erb
<div>
	<%= label_tag("detail_brand_id", "Choose brand name:") %>
	<%= collection_select(  :detail,
                          :brand_id,
                          Brand.all,
                          :id,
                          :name,
                          include_blank: true,
                          id: "xxx") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autogroup</title>
    <%= stylesheet_link_tag 'sass/materialize',
                            media: 'all',
                            'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'style_manifest.scss',
                            media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/bin/materialize.js',
                                 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/my_script.js',
                                 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
        <%= render 'layouts/nav' %>
        <div class="parallax-container">
            <div class="section no-pad-bot">
                <div class="row">
                  <div id="devise" >
                    <%= render 'layouts/devise' %>
                  </div>
                  <p class="notice"><%= notice %></p>
                  <p class="alert"><%= alert %></p>
                  <% unless (@cart.nil?) %>
                    <%= hidden_div_if( @cart.line_items.empty?, id: 'cart') do %>
                      <%= render @cart %>
                    <% end %>
                  <% end %>
                  <%= yield %>
                </div>
            </div>
            <div class="parallax">
              <%= image_tag("image6.jpg") %>
            </div>
        </div>
        <div class="section z-depth-3 secondaryColor ">
          <div class="section">

            <!--   Icon Section   -->
            <div class="row">
              <div class="col s12 m4 insertion">
                <div class="icon-block">
                  <h2 class="center brown-text"><i class="mdi-image-flash-on"></i></h2>
                  <h5 class="center">Speeds up development</h5>

                  <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
                </div>
              </div>

              <div class="col s12 m4 insertion">
                <div class="icon-block">
                  <h2 class="center brown-text"><i class="mdi-social-group"></i></h2>
                  <h5 class="center">User Experience Focused</h5>

                  <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
                </div>
              </div>

              <div class="col s12 m4 insertion">
                <div class="icon-block">
                  <h2 class="center brown-text"><i class="mdi-action-settings"></i></h2>
                  <h5 class="center">Easy to work with</h5>

                  <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="parallax-container">
          <div class="parallax">
            <%= image_tag("image1.jpg") %>
          </div>
        </div>
<!-- ####################### -->

        <div class="container">
          <div class="section">

            <!--   Icon Section   -->
            <div class="row">
              <div class="col s12 m4">
                <div class="icon-block">
                  <h2 class="center brown-text"><i class="mdi-image-flash-on"></i></h2>
                  <h5 class="center">Speeds up development</h5>

                  <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
                </div>
              </div>

              <div class="col s12 m4">
                <div class="icon-block">
                  <h2 class="center brown-text"><i class="mdi-social-group"></i></h2>
                  <h5 class="center">User Experience Focused</h5>

                  <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
                </div>
              </div>

              <div class="col s12 m4">
                <div class="icon-block">
                  <h2 class="center brown-text"><i class="mdi-action-settings"></i></h2>
                  <h5 class="center">Easy to work with</h5>

                  <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
                </div>
              </div>
            </div>

          </div>
        </div>

        <div id="index-banner" class="parallax-container">
          <div class="section no-pad-bot">

          </div>
          <div class="parallax"><%= image_tag("image2.jpg") %></div>
        </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Autogroup</title>
    <%= stylesheet_link_tag 'sass/materialize',
                            media: 'all',
                            'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'main',
                            media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/bin/materialize.js',
                                 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/my_script.js',
                                 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'details.js',
                                 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row">
      <%= render 'layouts/nav' %>
      <div id="container">
        <div id="upper">
          <div id="devise" data-user_id="<%= current_user.try(:id) %>">
            <%= render 'layouts/devise' %>
          </div>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <% unless (@cart.nil?) %>
            <%= hidden_div_if( @cart.line_items.empty?, id: 'cart') do %>
              <%= render @cart %>
            <% end %>
          <% end %>
        </div>
        <div id="yield">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>